### PR TITLE
Added SwiftPM support

### PR DESCRIPTION
**Pull request by colemancda**
Fixes SwiftPM and Mac Catalyst support (#118)

### CODE REVIEW

**Comment by JonasGessner** [comment]
What is the rationale for moving all the files into a different folder? And why is the module map file needed?

**Comment by colemancda** [comment]
The ObjC framework needs the required `include` folder and `module.modulemap` to make the headers public. Without that the code is compiled but there is no `JGProgressHUD` module defined.

**Comment by colemancda** [comment]
Also it seems the source code was not even compiling before, because the parent folder `./JGProgressHUD` was defined instead of `./JGProgressHUD/JGProgressHUD`

**Comment by JonasGessner** [comment]
A module [is defined](https://github.com/JonasGessner/JGProgressHUD/blob/master/Examples/JGProgressHUD-Tests/JGMainViewController.m#L12) though without these changes. I'll look into Catalyst support when I get time.

**Comment by colemancda** [comment]
SwiftPM forces a specific directory layout to compile ObjC source. The module you specify is defined when building from the dynamic framework (e.g. Carthage). You need the module file for SwiftPM since SwiftPM has no knowledge of the Xcode project and build settings.

**Comment by JonasGessner** [comment]
I just tested this with catalyst (by enabling catalyst support in the example project) and it works fine. SwiftPM seems to work too, at least with Accio. Unless I'm missing something I am going to close this. So please double check on your end and if anything isn't working let me know.

**Comment by colemancda** [comment]
Accio is third party, currently this does not build properly by just adding the Git URL to the project in Xcode 11, with the official iOS SwiftPM support.

**Comment by GottaGetSwifty** [comment]
Please merge this. Official SPM integration doesn't work as is. 

```
import JGProgressHUD 
...
JGProgressHUD()
```
Gets you an error: "Cannot call value of non-function type 'module<JGProgressHUD>'"

To reproduce:
- Start new project with Xcode 11
- File->Swift Packages->Add PackageDependency...
- Add JGProgressHUD git url and add the package
- import the module and attempt to use anywhere in the project

**Comment by JonasGessner** [comment]
Ok I just tested this and while Accio works, SwiftPM in Xcode 11 doesn't. Your changes seem fine, except it would break CocoaPods support currently (the s.source_files glob needs to be updated to be recursive) and one deal breaker is the fact that you can't bundle resources with SwiftPM, which essentially makes the success and error indicators unusable. Only real way to fix is to generate the images at runtime/use a CAShapeLayer.

**Comment by JonasGessner** [comment]
I made all the changes I mentioned in my last comment. Will release a new version now. Thanks for the contribution!

**Pull request merged**
