### PR TITLE
Add full width support

### PR DESCRIPTION
**Pull request by lairoeaes**

### CODE REVIEW

**Comment by JonasGessner** [comment]
What is the use for this feature? It doesn't really make sense!

**Comment by lairoeaes** [comment]
I want to show the toast like a full-width notification view on the top of the host view.
(For example: https://github.com/cruffenach/CRToast)

**Comment by JonasGessner** [comment]
Something like CRToast is very different from a HUD and JGProgressHUD is not meant to be used as a notification drop down. If I add a full width option I should probably also add a full height option and I don't want to add too many options. You should probably just use CRToast instead of a HUD!

**Comment by lairoeaes** [comment]
OK, thanks for your suggestion.

**Pull request closed without merging**
