### PR TITLE
Add identifier.

### PR DESCRIPTION
**Pull request by 0x0c**
I added hud identifier.
For example, it's used to dismiss in asynchronous procedure.

### CODE REVIEW

**Comment by JonasGessner** [comment]
Thats unnecessary. An object's memory address is a unique identifier already.
```objc
JGProgressHUD *hud1 = [JGProgressHUD new];
JGProgressHUD *hud2 = [JGProgressHUD new];

NSLog(@"%i", hud1 == hud2);
```

This will output `0`.

To get a string:
```objc
NSString *identifier = [NSString stringWithFormat:@"%p", hud];
```

**Comment by 0x0c** [comment]
I think it is necessary.
For example,

	for (NSURL *url in urls) {
		JGProgressHUD *HUD = [[JGProgressHUD alloc] initWithStyle:JGProgressHUDStyleDark];
		HUD.identifier = url.absoluteString;
		[HUD showInView:[[UIApplication sharedApplication].delegate window]];
		[NSURLConnection sendAsynchronousRequest:req queue:q completionHandler:^(NSURLResponse *response, NSData *data, NSError *connectionError) {
			for (JGProgressHUD *hud in [JGProgressHUD allProgressHUDsInView:[[UIApplication sharedApplication].delegate window]]) {
				if ([hud.identifier isEqualToString:request.URL.absoluteString]) {
					[hud dismissAnimated:YES];
				}
			}
		}];
	}

To dismiss, we have to know which hud is  shown by which connection.

**Comment by JonasGessner** [comment]
The easier and more efficient way:
```objc
for (NSURL *url in urls) {
    JGProgressHUD *HUD = [[JGProgressHUD alloc] initWithStyle:JGProgressHUDStyleDark];
    [HUD showInView:<Read the documentation, you shouldn't show the HUD in a UIWindow!!>];
     [NSURLConnection sendAsynchronousRequest:req queue:q completionHandler:^(NSURLResponse *response, NSData *data, NSError *connectionError) {
        [HUD dismissAnimated:YES];
    }];
}
```

How you should actually do it:
• Only show one HUD, showing multiple HUDs on top of each other is pretty ugly and confusing.
• Don't show the HUD in a UIWindow! Show it in a UIView managed by a UIViewController, so that the HUD respects the current interface orientation (On iOS 8 UIWindows are rotation-aware too, but it's still better to always show it in a UIViewController's view).
• Identify the HUD by its memory address!

```objc
NSUInteger expectedCount = urls.count;
if (expectedCount > 0) {
    JGProgressHUD *HUD = [[JGProgressHUD alloc] initWithStyle:JGProgressHUDStyleDark];
    [HUD showInView:yourViewController.view];
    for (NSURL *url in urls) {
        [NSURLConnection sendAsynchronousRequest:[NSURLRequest requestWithURL:url] queue:q completionHandler:^(NSURLResponse *response, NSData *data, NSError *connectionError) {
            expectedCount--;
            if (expectedCount == 0) {
                [HUD dismissAnimated:YES];
            }
        }];
    }
}
```

**Comment by 0x0c** [comment]
OK
I'll do that.
Thank you:)

**Pull request closed without merging**
